services:
  postgres:
    image: postgres:16
    container_name: pulseq-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pulseq
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command:
      - postgres
      - -c
      - timezone=UTC
      - -c
      - log_timezone=UTC
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: pulseq-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
